// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBCwRIt2k9Z5El3-SEh2fXl2a2dWOIS4',
    appId: '1:10341186416:web:09d26f8fe868bd773eedb5',
    messagingSenderId: '10341186416',
    projectId: 'flutter-basic-9dc8e',
    authDomain: 'flutter-basic-9dc8e.firebaseapp.com',
    storageBucket: 'flutter-basic-9dc8e.firebasestorage.app',
    measurementId: 'G-2KG873Q0FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPKblag1_Tik4u5m-HNctwFBgSsmDPIM8',
    appId: '1:10341186416:android:ca55ec14a50626283eedb5',
    messagingSenderId: '10341186416',
    projectId: 'flutter-basic-9dc8e',
    storageBucket: 'flutter-basic-9dc8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9eOkAXLS9Q0teHbLFb7XzMYydCJPeVcA',
    appId: '1:10341186416:ios:714d88223b0ca4453eedb5',
    messagingSenderId: '10341186416',
    projectId: 'flutter-basic-9dc8e',
    storageBucket: 'flutter-basic-9dc8e.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9eOkAXLS9Q0teHbLFb7XzMYydCJPeVcA',
    appId: '1:10341186416:ios:714d88223b0ca4453eedb5',
    messagingSenderId: '10341186416',
    projectId: 'flutter-basic-9dc8e',
    storageBucket: 'flutter-basic-9dc8e.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJBCwRIt2k9Z5El3-SEh2fXl2a2dWOIS4',
    appId: '1:10341186416:web:3997299580082d4b3eedb5',
    messagingSenderId: '10341186416',
    projectId: 'flutter-basic-9dc8e',
    authDomain: 'flutter-basic-9dc8e.firebaseapp.com',
    storageBucket: 'flutter-basic-9dc8e.firebasestorage.app',
    measurementId: 'G-2WR80DM889',
  );
}
